- name: Determine .app path
  id: ap
  run: |
    set -e
    BUILD_DIR="$PWD/build"

    # Mostrar settings usando el MISMO BUILD_DIR que el build
    SETTINGS=$(mktemp)
    xcodebuild \
      -project TeamsWeb.xcodeproj \
      -scheme TeamsWeb \
      -configuration Release \
      -sdk iphoneos \
      BUILD_DIR=$BUILD_DIR \
      -showBuildSettings > "$SETTINGS"

    # Parsear las rutas
    APP_DIR=$(awk -F ' = ' '/ TARGET_BUILD_DIR /{print $2; exit}' "$SETTINGS")
    WRAPPER=$(awk -F ' = ' '/ WRAPPER_NAME /{print $2; exit}' "$SETTINGS")
    APP_PATH="$APP_DIR/$WRAPPER"

    echo "TARGET_BUILD_DIR=$APP_DIR"
    echo "WRAPPER_NAME=$WRAPPER"
    echo "APP_PATH=$APP_PATH"

    # Si por algún motivo no existe, usar fallback directo al directorio de build
    if [ ! -d "$APP_PATH" ]; then
      ALT="$BUILD_DIR/Release-iphoneos/TeamsWeb.app"
      if [ -d "$ALT" ]; then
        APP_PATH="$ALT"
        echo "Usando fallback: $APP_PATH"
      else
        echo "❌ No se encontró el .app en $APP_PATH ni en $ALT"
        find "$BUILD_DIR" -name "TeamsWeb.app" -maxdepth 6 -type d -print || true
        exit 1
      fi
    fi

    echo "APP_PATH=$APP_PATH" >> "$GITHUB_OUTPUT"
